# Auto-generated — do not edit

BUILTIN_FUNCTIONS = {
    'EmitVertex': {'return': 'void', 'params': [], 'extensions': ['EXT_geometry_shader', 'OES_geometry_shader']},
    'EndPrimitive': {'return': 'void', 'params': [], 'extensions': ['EXT_geometry_shader', 'OES_geometry_shader']},
    'abs': {'return': 'genIType', 'params': ['genIType'], 'extensions': []},
    'acos': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'acosh': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'all': {'return': 'bool', 'params': ['bvec'], 'extensions': []},
    'any': {'return': 'bool', 'params': ['bvec'], 'extensions': []},
    'asin': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'asinh': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'atan': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'atanh': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'atomicAdd': {'return': 'int', 'params': ['int', 'int'], 'extensions': []},
    'atomicAnd': {'return': 'int', 'params': ['int', 'int'], 'extensions': []},
    'atomicCompSwap': {'return': 'int', 'params': ['int', 'int', 'int'], 'extensions': []},
    'atomicCounter': {'return': 'uint', 'params': ['atomic_uint'], 'extensions': []},
    'atomicCounterDecrement': {'return': 'uint', 'params': ['atomic_uint'], 'extensions': []},
    'atomicCounterIncrement': {'return': 'uint', 'params': ['atomic_uint'], 'extensions': []},
    'atomicExchange': {'return': 'int', 'params': ['int', 'int'], 'extensions': []},
    'atomicMax': {'return': 'int', 'params': ['int', 'int'], 'extensions': []},
    'atomicMin': {'return': 'int', 'params': ['int', 'int'], 'extensions': []},
    'atomicOr': {'return': 'int', 'params': ['int', 'int'], 'extensions': []},
    'atomicXor': {'return': 'int', 'params': ['int', 'int'], 'extensions': []},
    'barrier': {'return': 'void', 'params': [], 'extensions': ['EXT_tessellation_shader', 'OES_tessellation_shader']},
    'beginFragmentShaderOrderingINTEL': {'return': 'void', 'params': [], 'extensions': []},
    'beginInvocationInterlockARB': {'return': 'void', 'params': [], 'extensions': []},
    'beginInvocationInterlockNV': {'return': 'void', 'params': [], 'extensions': []},
    'bitCount': {'return': 'genIType', 'params': ['genUType'], 'extensions': []},
    'bitfieldExtract': {'return': 'genUType', 'params': ['genUType', 'int', 'int'], 'extensions': []},
    'bitfieldInsert': {'return': 'genUType', 'params': ['genUType', 'genUType', 'int', 'int'], 'extensions': []},
    'bitfieldReverse': {'return': 'genUType', 'params': ['genUType'], 'extensions': []},
    'ceil': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'clamp': {'return': 'genUType', 'params': ['genUType', 'genUType', 'genUType'], 'extensions': []},
    'cos': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'cosh': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'cross': {'return': 'vec3', 'params': ['vec3', 'vec3'], 'extensions': []},
    'dFdx': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'dFdy': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'degrees': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'determinant': {'return': 'float', 'params': ['mat4'], 'extensions': []},
    'distance': {'return': 'float', 'params': ['genType', 'genType'], 'extensions': []},
    'dot': {'return': 'float', 'params': ['genType', 'genType'], 'extensions': []},
    'endInvocationInterlockARB': {'return': 'void', 'params': [], 'extensions': []},
    'endInvocationInterlockNV': {'return': 'void', 'params': [], 'extensions': []},
    'equal': {'return': 'bvec', 'params': ['bvec', 'bvec'], 'extensions': []},
    'exp': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'exp2': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'faceforward': {'return': 'genType', 'params': ['genType', 'genType', 'genType'], 'extensions': []},
    'findLSB': {'return': 'genIType', 'params': ['genUType'], 'extensions': []},
    'findMSB': {'return': 'genIType', 'params': ['genUType'], 'extensions': []},
    'floatBitsToInt': {'return': 'genIType', 'params': ['genType'], 'extensions': []},
    'floatBitsToUint': {'return': 'genUType', 'params': ['genType'], 'extensions': []},
    'floor': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'fma': {'return': 'genType', 'params': ['genType', 'genType', 'genType'], 'extensions': ['EXT_gpu_shader5', 'OES_gpu_shader5']},
    'fract': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'frexp': {'return': 'genType', 'params': ['genType', 'genIType'], 'extensions': []},
    'fwidth': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'greaterThan': {'return': 'bvec', 'params': ['uvec', 'uvec'], 'extensions': []},
    'greaterThanEqual': {'return': 'bvec', 'params': ['uvec', 'uvec'], 'extensions': []},
    'groupMemoryBarrier': {'return': 'void', 'params': [], 'extensions': []},
    'imageAtomicAdd': {'return': 'int', 'params': ['IMAGE_PARAMS', 'int'], 'extensions': ['OES_shader_image_atomic']},
    'imageAtomicAnd': {'return': 'int', 'params': ['IMAGE_PARAMS', 'int'], 'extensions': ['OES_shader_image_atomic']},
    'imageAtomicCompSwap': {'return': 'int', 'params': ['IMAGE_PARAMS', 'int', 'int'], 'extensions': ['OES_shader_image_atomic']},
    'imageAtomicExchange': {'return': 'float', 'params': ['IMAGE_PARAMS', 'float'], 'extensions': ['OES_shader_image_atomic']},
    'imageAtomicMax': {'return': 'int', 'params': ['IMAGE_PARAMS', 'int'], 'extensions': ['OES_shader_image_atomic']},
    'imageAtomicMin': {'return': 'int', 'params': ['IMAGE_PARAMS', 'int'], 'extensions': ['OES_shader_image_atomic']},
    'imageAtomicOr': {'return': 'int', 'params': ['IMAGE_PARAMS', 'int'], 'extensions': ['OES_shader_image_atomic']},
    'imageAtomicXor': {'return': 'int', 'params': ['IMAGE_PARAMS', 'int'], 'extensions': ['OES_shader_image_atomic']},
    'imageLoad': {'return': 'gvec4', 'params': ['gimageBuffer', 'int'], 'extensions': ['OES_texture_buffer', 'EXT_texture_buffer']},
    'imageSize': {'return': 'int', 'params': ['gimageBuffer'], 'extensions': ['OES_texture_buffer', 'EXT_texture_buffer']},
    'imageStore': {'return': 'void', 'params': ['gimageBuffer', 'int', 'gvec4'], 'extensions': ['OES_texture_buffer', 'EXT_texture_buffer']},
    'imulExtended': {'return': 'void', 'params': ['genIType', 'genIType', 'genIType', 'genIType'], 'extensions': []},
    'intBitsToFloat': {'return': 'genType', 'params': ['genIType'], 'extensions': []},
    'interpolateAtCenter': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'interpolateAtCentroid': {'return': 'vec4', 'params': ['vec4'], 'extensions': ['OES_shader_multisample_interpolation']},
    'interpolateAtOffset': {'return': 'vec4', 'params': ['vec4', 'vec2'], 'extensions': ['OES_shader_multisample_interpolation']},
    'interpolateAtSample': {'return': 'vec4', 'params': ['vec4', 'int'], 'extensions': ['OES_shader_multisample_interpolation']},
    'inverse': {'return': 'mat4', 'params': ['mat4'], 'extensions': []},
    'inversesqrt': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'isinf': {'return': 'genBType', 'params': ['genType'], 'extensions': []},
    'isnan': {'return': 'genBType', 'params': ['genType'], 'extensions': []},
    'ldexp': {'return': 'genType', 'params': ['genType', 'genIType'], 'extensions': []},
    'length': {'return': 'float', 'params': ['genType'], 'extensions': []},
    'lessThan': {'return': 'bvec', 'params': ['uvec', 'uvec'], 'extensions': []},
    'lessThanEqual': {'return': 'bvec', 'params': ['uvec', 'uvec'], 'extensions': []},
    'log': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'log2': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'matrixCompMult': {'return': 'mat4x3', 'params': ['mat4x3', 'mat4x3'], 'extensions': []},
    'max': {'return': 'genUType', 'params': ['genUType', 'uint'], 'extensions': []},
    'memoryBarrier': {'return': 'void', 'params': [], 'extensions': []},
    'memoryBarrierAtomicCounter': {'return': 'void', 'params': [], 'extensions': []},
    'memoryBarrierBuffer': {'return': 'void', 'params': [], 'extensions': []},
    'memoryBarrierImage': {'return': 'void', 'params': [], 'extensions': []},
    'memoryBarrierShared': {'return': 'void', 'params': [], 'extensions': []},
    'min': {'return': 'genUType', 'params': ['genUType', 'uint'], 'extensions': []},
    'mix': {'return': 'genBType', 'params': ['genBType', 'genBType', 'genBType'], 'extensions': []},
    'mod': {'return': 'genType', 'params': ['genType', 'genType'], 'extensions': []},
    'modf': {'return': 'genType', 'params': ['genType', 'genType'], 'extensions': []},
    'normalize': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'not': {'return': 'bvec', 'params': ['bvec'], 'extensions': []},
    'notEqual': {'return': 'bvec', 'params': ['bvec', 'bvec'], 'extensions': []},
    'numSamples': {'return': 'uint', 'params': [], 'extensions': []},
    'outerProduct': {'return': 'mat4x3', 'params': ['vec3', 'vec4'], 'extensions': []},
    'packHalf2x16': {'return': 'uint', 'params': ['vec2'], 'extensions': []},
    'packSnorm2x16': {'return': 'uint', 'params': ['vec2'], 'extensions': []},
    'packSnorm4x8': {'return': 'uint', 'params': ['vec4'], 'extensions': []},
    'packUnorm2x16': {'return': 'uint', 'params': ['vec2'], 'extensions': []},
    'packUnorm4x8': {'return': 'uint', 'params': ['vec4'], 'extensions': []},
    'pixelLocalLoadANGLE': {'return': 'gvec4', 'params': ['gpixelLocalANGLE'], 'extensions': ['ANGLE_shader_pixel_local_storage']},
    'pixelLocalStoreANGLE': {'return': 'void', 'params': ['gpixelLocalANGLE', 'gvec4'], 'extensions': ['ANGLE_shader_pixel_local_storage']},
    'pow': {'return': 'genType', 'params': ['genType', 'genType'], 'extensions': []},
    'radians': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'reflect': {'return': 'genType', 'params': ['genType', 'genType'], 'extensions': []},
    'refract': {'return': 'genType', 'params': ['genType', 'genType', 'float'], 'extensions': []},
    'rgb_2_yuv': {'return': 'vec3', 'params': ['vec3', 'yuvCscStandardEXT'], 'extensions': ['EXT_YUV_target']},
    'round': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'roundEven': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'samplePosition': {'return': 'vec2', 'params': ['uint'], 'extensions': []},
    'saturate': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'shadow2DEXT': {'return': 'float', 'params': ['sampler2DShadow', 'vec3'], 'extensions': ['EXT_shadow_samplers']},
    'shadow2DProjEXT': {'return': 'float', 'params': ['sampler2DShadow', 'vec4'], 'extensions': ['EXT_shadow_samplers']},
    'sign': {'return': 'genIType', 'params': ['genIType'], 'extensions': []},
    'sin': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'sinh': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'smoothstep': {'return': 'genType', 'params': ['float', 'float', 'genType'], 'extensions': []},
    'sqrt': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'step': {'return': 'genType', 'params': ['float', 'genType'], 'extensions': []},
    'subpassLoad': {'return': 'gvec4', 'params': ['gsubpassInput'], 'extensions': []},
    'tan': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'tanh': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'texelFetch': {'return': 'vec4', 'params': ['samplerExternal2DY2YEXT', 'ivec2', 'int'], 'extensions': ['EXT_YUV_target']},
    'texelFetchOffset': {'return': 'gvec4', 'params': ['gsampler2DArray', 'ivec3', 'int', 'ivec2'], 'extensions': []},
    'texture': {'return': 'vec4', 'params': ['samplerExternal2DY2YEXT', 'vec2', 'float'], 'extensions': ['EXT_YUV_target']},
    'texture2D': {'return': 'vec4', 'params': ['sampler2D', 'vec2', 'float'], 'extensions': []},
    'texture2DGradEXT': {'return': 'vec4', 'params': ['sampler2D', 'vec2', 'vec2', 'vec2'], 'extensions': ['EXT_shader_texture_lod']},
    'texture2DLod': {'return': 'vec4', 'params': ['sampler2D', 'vec2', 'float'], 'extensions': []},
    'texture2DLodEXT': {'return': 'vec4', 'params': ['sampler2D', 'vec2', 'float'], 'extensions': ['EXT_shader_texture_lod']},
    'texture2DProj': {'return': 'vec4', 'params': ['sampler2D', 'vec4', 'float'], 'extensions': []},
    'texture2DProjGradEXT': {'return': 'vec4', 'params': ['sampler2D', 'vec4', 'vec2', 'vec2'], 'extensions': ['EXT_shader_texture_lod']},
    'texture2DProjLod': {'return': 'vec4', 'params': ['sampler2D', 'vec4', 'float'], 'extensions': []},
    'texture2DProjLodEXT': {'return': 'vec4', 'params': ['sampler2D', 'vec4', 'float'], 'extensions': ['EXT_shader_texture_lod']},
    'texture2DRect': {'return': 'vec4', 'params': ['sampler2DRect', 'vec2'], 'extensions': ['ARB_texture_rectangle']},
    'texture2DRectProj': {'return': 'vec4', 'params': ['sampler2DRect', 'vec4'], 'extensions': ['ARB_texture_rectangle']},
    'texture3D': {'return': 'vec4', 'params': ['sampler3D', 'vec3', 'float'], 'extensions': ['OES_texture_3D']},
    'texture3DLod': {'return': 'vec4', 'params': ['sampler3D', 'vec3', 'float'], 'extensions': ['OES_texture_3D']},
    'texture3DProj': {'return': 'vec4', 'params': ['sampler3D', 'vec4', 'float'], 'extensions': ['OES_texture_3D']},
    'texture3DProjLod': {'return': 'vec4', 'params': ['sampler3D', 'vec4', 'float'], 'extensions': ['OES_texture_3D']},
    'textureCube': {'return': 'vec4', 'params': ['samplerCube', 'vec3', 'float'], 'extensions': []},
    'textureCubeGradEXT': {'return': 'vec4', 'params': ['samplerCube', 'vec3', 'vec3', 'vec3'], 'extensions': ['EXT_shader_texture_lod']},
    'textureCubeLod': {'return': 'vec4', 'params': ['samplerCube', 'vec3', 'float'], 'extensions': []},
    'textureCubeLodEXT': {'return': 'vec4', 'params': ['samplerCube', 'vec3', 'float'], 'extensions': ['EXT_shader_texture_lod']},
    'textureGather': {'return': 'vec4', 'params': ['samplerCubeShadow', 'vec3', 'float'], 'extensions': []},
    'textureGatherOffset': {'return': 'vec4', 'params': ['sampler2DArrayShadow', 'vec3', 'float', 'ivec2'], 'extensions': []},
    'textureGatherOffsets': {'return': 'vec4', 'params': ['sampler2DArrayShadow', 'vec3', 'float', 'ivec2[4]'], 'extensions': ['EXT_gpu_shader5', 'OES_gpu_shader5']},
    'textureGrad': {'return': 'gvec4', 'params': ['gsamplerCubeArray', 'vec4', 'vec3', 'vec3'], 'extensions': ['OES_texture_cube_map_array', 'EXT_texture_cube_map_array']},
    'textureGradOffset': {'return': 'float', 'params': ['sampler2DArrayShadow', 'vec4', 'vec2', 'vec2', 'ivec2'], 'extensions': []},
    'textureLod': {'return': 'gvec4', 'params': ['gsamplerCubeArray', 'vec4', 'float'], 'extensions': ['OES_texture_cube_map_array', 'EXT_texture_cube_map_array']},
    'textureLodOffset': {'return': 'float', 'params': ['sampler2DArrayShadow', 'vec4', 'float', 'ivec2'], 'extensions': ['EXT_texture_shadow_lod']},
    'textureOffset': {'return': 'float', 'params': ['sampler2DArrayShadow', 'vec4', 'ivec2', 'float'], 'extensions': ['EXT_texture_shadow_lod']},
    'textureProj': {'return': 'vec4', 'params': ['samplerExternal2DY2YEXT', 'vec4', 'float'], 'extensions': ['EXT_YUV_target']},
    'textureProjGrad': {'return': 'float', 'params': ['sampler2DShadow', 'vec4', 'vec2', 'vec2'], 'extensions': []},
    'textureProjGradOffset': {'return': 'float', 'params': ['sampler2DShadow', 'vec4', 'vec2', 'vec2', 'ivec2'], 'extensions': []},
    'textureProjLod': {'return': 'float', 'params': ['sampler2DShadow', 'vec4', 'float'], 'extensions': []},
    'textureProjLodOffset': {'return': 'float', 'params': ['sampler2DShadow', 'vec4', 'float', 'ivec2'], 'extensions': []},
    'textureProjOffset': {'return': 'float', 'params': ['sampler2DShadow', 'vec4', 'ivec2', 'float'], 'extensions': []},
    'textureQueryLOD': {'return': 'vec2', 'params': ['samplerCubeArrayShadow', 'vec3'], 'extensions': ['EXT_texture_query_lod']},
    'textureSize': {'return': 'ivec2', 'params': ['samplerExternal2DY2YEXT', 'int'], 'extensions': ['EXT_YUV_target']},
    'textureVideoWEBGL': {'return': 'vec4', 'params': ['samplerVideoWEBGL', 'vec2'], 'extensions': []},
    'transpose': {'return': 'mat4x3', 'params': ['mat3x4'], 'extensions': []},
    'trunc': {'return': 'genType', 'params': ['genType'], 'extensions': []},
    'uaddCarry': {'return': 'genUType', 'params': ['genUType', 'genUType', 'genUType'], 'extensions': []},
    'uintBitsToFloat': {'return': 'genType', 'params': ['genUType'], 'extensions': []},
    'umulExtended': {'return': 'void', 'params': ['genUType', 'genUType', 'genUType', 'genUType'], 'extensions': []},
    'unpackHalf2x16': {'return': 'vec2', 'params': ['uint'], 'extensions': []},
    'unpackSnorm2x16': {'return': 'vec2', 'params': ['uint'], 'extensions': []},
    'unpackSnorm4x8': {'return': 'vec4', 'params': ['uint'], 'extensions': []},
    'unpackUnorm2x16': {'return': 'vec2', 'params': ['uint'], 'extensions': []},
    'unpackUnorm4x8': {'return': 'vec4', 'params': ['uint'], 'extensions': []},
    'usubBorrow': {'return': 'genUType', 'params': ['genUType', 'genUType', 'genUType'], 'extensions': []},
    'yuv_2_rgb': {'return': 'vec3', 'params': ['vec3', 'yuvCscStandardEXT'], 'extensions': ['EXT_YUV_target']},
}
