SamplerState       g_sSamp : register(s0);
uniform Texture1D <float4> g_tTex1df4 : register(t0);
Texture1D <int4>   g_tTex1di4;
Texture1D <uint4>  g_tTex1du4;
Texture2D <float4> g_tTex2df4;
Texture2D <int4>   g_tTex2di4;
Texture2D <uint4>  g_tTex2du4;
Texture3D <float4> g_tTex3df4;
Texture3D <int4>   g_tTex3di4;
Texture3D <uint4>  g_tTex3du4;
TextureCube <float4> g_tTexcdf4;
TextureCube <int4>   g_tTexcdi4;
TextureCube <uint4>  g_tTexcdu4;
Texture1DArray <float4> g_tTex1df4a;
Texture1DArray <int4>   g_tTex1di4a;
Texture1DArray <uint4>  g_tTex1du4a;
Texture2DArray <float4> g_tTex2df4a;
Texture2DArray <int4>   g_tTex2di4a;
Texture2DArray <uint4>  g_tTex2du4a;
TextureCubeArray <float4> g_tTexcdf4a;
TextureCubeArray <int4>   g_tTexcdi4a;
TextureCubeArray <uint4>  g_tTexcdu4a;
Texture2DMS <float4> g_tTex2dmsf4;
Texture2DMS <int4>   g_tTex2dmsi4;
Texture2DMS <uint4>  g_tTex2dmsu4;
Texture2DMSArray <float4> g_tTex2dmsf4a;
Texture2DMSArray <int4>   g_tTex2dmsi4a;
Texture2DMSArray <uint4>  g_tTex2dmsu4a;
struct PS_OUTPUT
{
    float4 Color : SV_Target0;
    float  Depth : SV_Depth;
};
PS_OUTPUT main()
{
   PS_OUTPUT psout;
   uint MipLevel;
   uint WidthU;
   uint HeightU;
   uint ElementsU;
   uint DepthU;
   uint NumberOfLevelsU;
   uint NumberOfSamplesU;
   float WidthF;
   float HeightF;
   float ElementsF;
   float DepthF;
   float NumberOfLevelsF;
   float NumberOfSamplesF;
   g_tTex1df4 . GetDimensions(WidthU);
   g_tTex1df4 . GetDimensions(6, WidthU, NumberOfLevelsU);
   g_tTex1di4 . GetDimensions(WidthU);
   g_tTex1di4 . GetDimensions(6, WidthU, NumberOfLevelsU);
   g_tTex1du4 . GetDimensions(WidthU);
   g_tTex1du4 . GetDimensions(6, WidthU, NumberOfLevelsU);
   g_tTex1df4a . GetDimensions(WidthU, ElementsU);
   g_tTex1df4a . GetDimensions(6, WidthU, ElementsU, NumberOfLevelsU);
   g_tTex1di4a . GetDimensions(WidthU, ElementsU);
   g_tTex1di4a . GetDimensions(6, WidthU, ElementsU, NumberOfLevelsU);
   g_tTex1du4a . GetDimensions(WidthU, ElementsU);
   g_tTex1du4a . GetDimensions(6, WidthU, ElementsU, NumberOfLevelsU);
   g_tTex2df4 . GetDimensions(WidthU, HeightU);
   g_tTex2df4 . GetDimensions(6, WidthU, HeightU, NumberOfLevelsU);
   g_tTex2di4 . GetDimensions(WidthU, HeightU);
   g_tTex2di4 . GetDimensions(6, WidthU, HeightU, NumberOfLevelsU);
   g_tTex2du4 . GetDimensions(WidthU, HeightU);
   g_tTex2du4 . GetDimensions(6, WidthU, HeightU, NumberOfLevelsU);
   g_tTex2df4a . GetDimensions(WidthU, HeightU, ElementsU);
   g_tTex2df4a . GetDimensions(6, WidthU, HeightU, ElementsU, NumberOfLevelsU);
   g_tTex2di4a . GetDimensions(WidthU, HeightU, ElementsU);
   g_tTex2di4a . GetDimensions(6, WidthU, HeightU, ElementsU, NumberOfLevelsU);
   g_tTex2du4a . GetDimensions(WidthU, HeightU, ElementsU);
   g_tTex2du4a . GetDimensions(6, WidthU, HeightU, ElementsU, NumberOfLevelsU);
   g_tTex3df4 . GetDimensions(WidthU, HeightU, DepthU);
   g_tTex3df4 . GetDimensions(6, WidthU, HeightU, DepthU, NumberOfLevelsU);
   g_tTex3di4 . GetDimensions(WidthU, HeightU, DepthU);
   g_tTex3di4 . GetDimensions(6, WidthU, HeightU, DepthU, NumberOfLevelsU);
   g_tTex3du4 . GetDimensions(WidthU, HeightU, DepthU);
   g_tTex3du4 . GetDimensions(6, WidthU, HeightU, DepthU, NumberOfLevelsU);
   g_tTexcdf4 . GetDimensions(WidthU, HeightU);
   g_tTexcdf4 . GetDimensions(6, WidthU, HeightU, NumberOfLevelsU);
   g_tTexcdi4 . GetDimensions(WidthU, HeightU);
   g_tTexcdi4 . GetDimensions(6, WidthU, HeightU, NumberOfLevelsU);
   g_tTexcdu4 . GetDimensions(WidthU, HeightU);
   g_tTexcdu4 . GetDimensions(6, WidthU, HeightU, NumberOfLevelsU);
   g_tTexcdf4a . GetDimensions(WidthU, HeightU, ElementsU);
   g_tTexcdf4a . GetDimensions(6, WidthU, HeightU, ElementsU, NumberOfLevelsU);
   g_tTexcdi4a . GetDimensions(WidthU, HeightU, ElementsU);
   g_tTexcdi4a . GetDimensions(6, WidthU, HeightU, ElementsU, NumberOfLevelsU);
   g_tTexcdu4a . GetDimensions(WidthU, HeightU, ElementsU);
   g_tTexcdu4a . GetDimensions(6, WidthU, HeightU, ElementsU, NumberOfLevelsU);
   g_tTex2dmsf4 . GetDimensions(WidthU, HeightU, NumberOfSamplesU);
   g_tTex2dmsi4 . GetDimensions(WidthU, HeightU, NumberOfSamplesU);
   g_tTex2dmsu4 . GetDimensions(WidthU, HeightU, NumberOfSamplesU);
   g_tTex2dmsf4a . GetDimensions(WidthU, HeightU, ElementsU, NumberOfSamplesU);
   g_tTex2dmsi4a . GetDimensions(WidthU, HeightU, ElementsU, NumberOfSamplesU);
   g_tTex2dmsu4a . GetDimensions(WidthU, HeightU, ElementsU, NumberOfSamplesU);
   g_tTex1df4 . GetDimensions(WidthF);
   g_tTex1df4 . GetDimensions(6, WidthF, NumberOfLevelsF);
   g_tTex1di4 . GetDimensions(WidthF);
   g_tTex1di4 . GetDimensions(6, WidthF, NumberOfLevelsF);
   g_tTex1du4 . GetDimensions(WidthF);
   g_tTex1du4 . GetDimensions(6, WidthF, NumberOfLevelsF);
   g_tTex1df4a . GetDimensions(WidthF, ElementsF);
   g_tTex1df4a . GetDimensions(6, WidthF, ElementsF, NumberOfLevelsF);
   g_tTex1di4a . GetDimensions(WidthF, ElementsF);
   g_tTex1di4a . GetDimensions(6, WidthF, ElementsF, NumberOfLevelsF);
   g_tTex1du4a . GetDimensions(WidthF, ElementsF);
   g_tTex1du4a . GetDimensions(6, WidthF, ElementsF, NumberOfLevelsF);
   g_tTex2df4 . GetDimensions(WidthF, HeightF);
   g_tTex2df4 . GetDimensions(6, WidthF, HeightF, NumberOfLevelsF);
   g_tTex2di4 . GetDimensions(WidthF, HeightF);
   g_tTex2di4 . GetDimensions(6, WidthF, HeightF, NumberOfLevelsF);
   g_tTex2du4 . GetDimensions(WidthF, HeightF);
   g_tTex2du4 . GetDimensions(6, WidthF, HeightF, NumberOfLevelsF);
   g_tTex2df4a . GetDimensions(WidthF, HeightF, ElementsF);
   g_tTex2df4a . GetDimensions(6, WidthF, HeightF, ElementsF, NumberOfLevelsF);
   g_tTex2di4a . GetDimensions(WidthF, HeightF, ElementsF);
   g_tTex2di4a . GetDimensions(6, WidthF, HeightF, ElementsF, NumberOfLevelsF);
   g_tTex2du4a . GetDimensions(WidthF, HeightF, ElementsF);
   g_tTex2du4a . GetDimensions(6, WidthF, HeightF, ElementsF, NumberOfLevelsF);
   g_tTex3df4 . GetDimensions(WidthF, HeightF, DepthF);
   g_tTex3df4 . GetDimensions(6, WidthF, HeightF, DepthF, NumberOfLevelsF);
   g_tTex3di4 . GetDimensions(WidthF, HeightF, DepthF);
   g_tTex3di4 . GetDimensions(6, WidthF, HeightF, DepthF, NumberOfLevelsF);
   g_tTex3du4 . GetDimensions(WidthF, HeightF, DepthF);
   g_tTex3du4 . GetDimensions(6, WidthF, HeightF, DepthF, NumberOfLevelsF);
   g_tTexcdf4 . GetDimensions(WidthF, HeightF);
   g_tTexcdf4 . GetDimensions(6, WidthF, HeightF, NumberOfLevelsF);
   g_tTexcdi4 . GetDimensions(WidthF, HeightF);
   g_tTexcdi4 . GetDimensions(6, WidthF, HeightF, NumberOfLevelsF);
   g_tTexcdu4 . GetDimensions(WidthF, HeightF);
   g_tTexcdu4 . GetDimensions(6, WidthF, HeightF, NumberOfLevelsF);
   g_tTexcdf4a . GetDimensions(WidthF, HeightF, ElementsF);
   g_tTexcdf4a . GetDimensions(6, WidthF, HeightF, ElementsF, NumberOfLevelsF);
   g_tTexcdi4a . GetDimensions(WidthF, HeightF, ElementsF);
   g_tTexcdi4a . GetDimensions(6, WidthF, HeightF, ElementsF, NumberOfLevelsF);
   g_tTexcdu4a . GetDimensions(WidthF, HeightF, ElementsF);
   g_tTexcdu4a . GetDimensions(6, WidthF, HeightF, ElementsF, NumberOfLevelsF);
   g_tTex2dmsf4 . GetDimensions(WidthF, HeightF, NumberOfSamplesF);
   g_tTex2dmsi4 . GetDimensions(WidthF, HeightF, NumberOfSamplesF);
   g_tTex2dmsu4 . GetDimensions(WidthF, HeightF, NumberOfSamplesF);
   g_tTex2dmsf4a . GetDimensions(WidthF, HeightF, ElementsF, NumberOfSamplesF);
   g_tTex2dmsi4a . GetDimensions(WidthF, HeightF, ElementsF, NumberOfSamplesF);
   g_tTex2dmsu4a . GetDimensions(WidthF, HeightF, ElementsF, NumberOfSamplesF);
   psout.Color = 1.0;
   psout.Depth = 1.0;
   return psout;
}
